[package]
name = "bme680-rs"
version = "0.1.0"
edition = "2024"
description = "a minimal no_std driver for bme68x environmental sensors"
license = "MIT OR Apache-2.0"
repository = "https://github.com/realoksi/bme680-rs"
keywords = ["embedded-hal", "no_std", "bme680", "bme688", "sensor"]
categories = ["embedded", "no-std::no-alloc", "hardware-support"]
readme = "README.md"

[dependencies]
paste = "1.0.15"
embedded-hal = { version = "1.0.0", default-features = false }

[dev-dependencies]
embedded-hal-mock = { version = "0.11.1", features = ["eh1"] }